// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/getdata_message.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Messages
{

    /// <summary>Holder for reflection information generated from protos/getdata_message.proto</summary>
    public static partial class GetdataMessageReflection
    {

        #region Descriptor
        /// <summary>File descriptor for protos/getdata_message.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static GetdataMessageReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "Chxwcm90b3MvZ2V0ZGF0YV9tZXNzYWdlLnByb3RvEhhwcm90b2J1Zl91bml0",
                  "dGVzdF9pbXBvcnQiFwoHR2V0RGF0YRIMCgRoYXNoGAEgASgMQhuqAhhHb29n",
                  "bGUuUHJvdG9idWYuTWVzc2FnZXNiBnByb3RvMw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Messages.GetData), global::Google.Protobuf.Messages.GetData.Parser, new[]{ "Hash" }, null, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class GetData : pb::IMessage<GetData>
    {
        private static readonly pb::MessageParser<GetData> _parser = new pb::MessageParser<GetData>(() => new GetData());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<GetData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Google.Protobuf.Messages.GetdataMessageReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GetData()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GetData(GetData other) : this()
        {
            hash_ = other.hash_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GetData Clone()
        {
            return new GetData(this);
        }

        /// <summary>Field number for the "hash" field.</summary>
        public const int HashFieldNumber = 1;
        private pb::ByteString hash_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pb::ByteString Hash
        {
            get { return hash_; }
            set
            {
                hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as GetData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(GetData other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Hash != other.Hash) return false;
            return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Hash.Length != 0) hash ^= Hash.GetHashCode();
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (Hash.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteBytes(Hash);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Hash.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Hash);
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(GetData other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Hash.Length != 0)
            {
                Hash = other.Hash;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        input.SkipLastField();
                        break;
                    case 10:
                        {
                            Hash = input.ReadBytes();
                            break;
                        }
                }
            }
        }

    }

    #endregion

}

#endregion Designer generated code
