// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/inv_message.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Messages
{

    /// <summary>Holder for reflection information generated from protos/inv_message.proto</summary>
    public static partial class InvMessageReflection
    {

        #region Descriptor
        /// <summary>File descriptor for protos/inv_message.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static InvMessageReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "Chhwcm90b3MvaW52X21lc3NhZ2UucHJvdG8SGHByb3RvYnVmX3VuaXR0ZXN0",
                  "X2ltcG9ydCIbCgRIYXNoEhMKC2hhc2hfZGlnaXRzGAEgASgMIjUKA0ludhIu",
                  "CgZoYXNoZXMYASADKAsyHi5wcm90b2J1Zl91bml0dGVzdF9pbXBvcnQuSGFz",
                  "aEIbqgIYR29vZ2xlLlByb3RvYnVmLk1lc3NhZ2VzYgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Messages.Hash), global::Google.Protobuf.Messages.Hash.Parser, new[]{ "HashDigits" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Messages.Inv), global::Google.Protobuf.Messages.Inv.Parser, new[]{ "Hashes" }, null, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class Hash : pb::IMessage<Hash>
    {
        private static readonly pb::MessageParser<Hash> _parser = new pb::MessageParser<Hash>(() => new Hash());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Hash> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Google.Protobuf.Messages.InvMessageReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Hash()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Hash(Hash other) : this()
        {
            hashDigits_ = other.hashDigits_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Hash Clone()
        {
            return new Hash(this);
        }

        /// <summary>Field number for the "hash_digits" field.</summary>
        public const int HashDigitsFieldNumber = 1;
        private pb::ByteString hashDigits_ = pb::ByteString.Empty;
        /// <summary>
        ///  This has to change to repeated int32 hash_digits = 1 after that change is done in Dafny
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pb::ByteString HashDigits
        {
            get { return hashDigits_; }
            set
            {
                hashDigits_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as Hash);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Hash other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (HashDigits != other.HashDigits) return false;
            return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (HashDigits.Length != 0) hash ^= HashDigits.GetHashCode();
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (HashDigits.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteBytes(HashDigits);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (HashDigits.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(HashDigits);
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Hash other)
        {
            if (other == null)
            {
                return;
            }
            if (other.HashDigits.Length != 0)
            {
                HashDigits = other.HashDigits;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        input.SkipLastField();
                        break;
                    case 10:
                        {
                            HashDigits = input.ReadBytes();
                            break;
                        }
                }
            }
        }

    }

    public sealed partial class Inv : pb::IMessage<Inv>
    {
        private static readonly pb::MessageParser<Inv> _parser = new pb::MessageParser<Inv>(() => new Inv());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Inv> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Google.Protobuf.Messages.InvMessageReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Inv()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Inv(Inv other) : this()
        {
            hashes_ = other.hashes_.Clone();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Inv Clone()
        {
            return new Inv(this);
        }

        /// <summary>Field number for the "hashes" field.</summary>
        public const int HashesFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Google.Protobuf.Messages.Hash> _repeated_hashes_codec
            = pb::FieldCodec.ForMessage(10, global::Google.Protobuf.Messages.Hash.Parser);
        private readonly pbc::RepeatedField<global::Google.Protobuf.Messages.Hash> hashes_ = new pbc::RepeatedField<global::Google.Protobuf.Messages.Hash>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Google.Protobuf.Messages.Hash> Hashes
        {
            get { return hashes_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as Inv);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Inv other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!hashes_.Equals(other.hashes_)) return false;
            return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= hashes_.GetHashCode();
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            hashes_.WriteTo(output, _repeated_hashes_codec);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            size += hashes_.CalculateSize(_repeated_hashes_codec);
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Inv other)
        {
            if (other == null)
            {
                return;
            }
            hashes_.Add(other.hashes_);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        input.SkipLastField();
                        break;
                    case 10:
                        {
                            hashes_.AddEntriesFrom(input, _repeated_hashes_codec);
                            break;
                        }
                }
            }
        }

    }

    #endregion

}

#endregion Designer generated code
