// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/wrapper_message.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Messages
{

    /// <summary>Holder for reflection information generated from protos/wrapper_message.proto</summary>
    public static partial class WrapperMessageReflection
    {

        #region Descriptor
        /// <summary>File descriptor for protos/wrapper_message.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static WrapperMessageReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "Chxwcm90b3Mvd3JhcHBlcl9tZXNzYWdlLnByb3RvEhhwcm90b2J1Zl91bml0",
                  "dGVzdF9pbXBvcnQi2AEKDldyYXBwZXJNZXNzYWdlEkIKBHR5cGUYASABKA4y",
                  "NC5wcm90b2J1Zl91bml0dGVzdF9pbXBvcnQuV3JhcHBlck1lc3NhZ2UuTWVz",
                  "c2FnZVR5cGUSDwoHcGF5bG9hZBgCIAEoDBIMCgRmcm9tGAMgASgFImMKC01l",
                  "c3NhZ2VUeXBlEg8KC1RSQU5TQUNUSU9OEAASCAoEQUREUhABEgcKA0lOVhAC",
                  "EgkKBUJMT0NLEAMSCwoHR0VUREFUQRAEEgsKB0NPTk5FQ1QQBRILCgdVTktO",
                  "T1dOEAZCG6oCGEdvb2dsZS5Qcm90b2J1Zi5NZXNzYWdlc2IGcHJvdG8z"));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Messages.WrapperMessage), global::Google.Protobuf.Messages.WrapperMessage.Parser, new[]{ "Type", "Payload", "From" }, null, new[]{ typeof(global::Google.Protobuf.Messages.WrapperMessage.Types.MessageType) }, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class WrapperMessage : pb::IMessage<WrapperMessage>
    {
        private static readonly pb::MessageParser<WrapperMessage> _parser = new pb::MessageParser<WrapperMessage>(() => new WrapperMessage());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<WrapperMessage> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Google.Protobuf.Messages.WrapperMessageReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WrapperMessage()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WrapperMessage(WrapperMessage other) : this()
        {
            type_ = other.type_;
            payload_ = other.payload_;
            from_ = other.from_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WrapperMessage Clone()
        {
            return new WrapperMessage(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private global::Google.Protobuf.Messages.WrapperMessage.Types.MessageType type_ = 0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Google.Protobuf.Messages.WrapperMessage.Types.MessageType Type
        {
            get { return type_; }
            set
            {
                type_ = value;
            }
        }

        /// <summary>Field number for the "payload" field.</summary>
        public const int PayloadFieldNumber = 2;
        private pb::ByteString payload_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pb::ByteString Payload
        {
            get { return payload_; }
            set
            {
                payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "from" field.</summary>
        public const int FromFieldNumber = 3;
        private int from_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int From
        {
            get { return from_; }
            set
            {
                from_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as WrapperMessage);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(WrapperMessage other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Type != other.Type) return false;
            if (Payload != other.Payload) return false;
            if (From != other.From) return false;
            return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Type != 0) hash ^= Type.GetHashCode();
            if (Payload.Length != 0) hash ^= Payload.GetHashCode();
            if (From != 0) hash ^= From.GetHashCode();
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (Type != 0)
            {
                output.WriteRawTag(8);
                output.WriteEnum((int)Type);
            }
            if (Payload.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteBytes(Payload);
            }
            if (From != 0)
            {
                output.WriteRawTag(24);
                output.WriteInt32(From);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Type != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
            }
            if (Payload.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
            }
            if (From != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(From);
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(WrapperMessage other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Type != 0)
            {
                Type = other.Type;
            }
            if (other.Payload.Length != 0)
            {
                Payload = other.Payload;
            }
            if (other.From != 0)
            {
                From = other.From;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        input.SkipLastField();
                        break;
                    case 8:
                        {
                            type_ = (global::Google.Protobuf.Messages.WrapperMessage.Types.MessageType)input.ReadEnum();
                            break;
                        }
                    case 18:
                        {
                            Payload = input.ReadBytes();
                            break;
                        }
                    case 24:
                        {
                            From = input.ReadInt32();
                            break;
                        }
                }
            }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the WrapperMessage message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types
        {
            public enum MessageType
            {
                [pbr::OriginalName("TRANSACTION")] Transaction = 0,
                [pbr::OriginalName("ADDR")] Addr = 1,
                [pbr::OriginalName("INV")] Inv = 2,
                [pbr::OriginalName("BLOCK")] Block = 3,
                [pbr::OriginalName("GETDATA")] Getdata = 4,
                [pbr::OriginalName("CONNECT")] Connect = 5,
                [pbr::OriginalName("UNKNOWN")] Unknown = 6,
            }

        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
